name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Run backend linter
        working-directory: backend
        run: npm run lint || echo "No backend lint script yet"

      - name: Skip backend tests
        run: echo "Skipping backend tests"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run frontend linter
        working-directory: frontend
        run: npm run lint || echo "No frontend lint script yet"

      - name: Skip frontend tests
        run: echo "Skipping frontend tests"
