name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

env:
  REGISTRY_NAME: todolistacr123.azurecr.io
  FRONTEND_IMAGE: todo-lite-frontend
  BACKEND_IMAGE: todo-lite-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # ----- FRONTEND -----
      - name: Install & Audit Frontend Dependencies
        working-directory: frontend
        run: |
          npm install
          npm audit --audit-level=high

      - name: Build Frontend Docker Image
        run: |
          docker build -t $REGISTRY_NAME/$FRONTEND_IMAGE:latest ./frontend

      # ----- BACKEND -----
      - name: Install & Audit Backend Dependencies
        working-directory: backend
        run: |
          npm install
          npm audit --audit-level=high

      - name: Build Backend Docker Image
        run: |
          docker build -t $REGISTRY_NAME/$BACKEND_IMAGE:latest ./backend

      # ----- PUSH IMAGES -----
      - name: Push Frontend Docker Image
        run: docker push $REGISTRY_NAME/$FRONTEND_IMAGE:latest

      - name: Push Backend Docker Image
        run: docker push $REGISTRY_NAME/$BACKEND_IMAGE:latest

      # ----- SECURITY SCANS -----
      - name: Scan Frontend Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY_NAME }}/${{ env.FRONTEND_IMAGE }}:latest
          format: table
          severity: CRITICAL,HIGH

      - name: Scan Backend Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY_NAME }}/${{ env.BACKEND_IMAGE }}:latest
          format: table
          severity: CRITICAL,HIGH

      - name: Fail if any scan fails
        run: exit 1
        if: failure()

      # ----- CONDITIONAL DEPLOYMENT -----
      - name: Deploy to Azure (Staging)
        if: github.ref == 'refs/heads/develop'
        uses: azure/webapps-deploy@v2
        with:
          app-name: tic-toc-frontend-staging
          images: ${{ env.REGISTRY_NAME }}/${{ env.FRONTEND_IMAGE }}:latest

      - name: Deploy to Azure (Staging Backend)
        if: github.ref == 'refs/heads/develop'
        uses: azure/webapps-deploy@v2
        with:
          app-name: todolite-backend-staging
          images: ${{ env.REGISTRY_NAME }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Deploy to Azure (Production Frontend)
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: tic-toc-frontend
          images: ${{ env.REGISTRY_NAME }}/${{ env.FRONTEND_IMAGE }}:latest

      - name: Deploy to Azure (Production Backend)
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: todolite-backend
          images: ${{ env.REGISTRY_NAME }}/${{ env.BACKEND_IMAGE }}:latest
